### ISSUE TITLE
Need help to run this Project

### ISSUE THREAD

**Issue by r00tshaim** [Abdullah1428/Proshop_Mern_MobileApp#1]
I don't have yarn installed, I am using npm 

i tried 
```
$ npm react-native run-android
Unknown command: "react-native"

To see a list of supported npm commands, run:
  npm help
```

installed react-native with `npm install react-native` still same error as above

How can we run this project with expo ?

**Comment by Abdullah1428** [comment]
Hi, this project is built using React Native CLI and not expo.

So, to run this project you need to setup [react-native cli](https://reactnative.dev/docs/environment-setup) on your local machine and also install [android-studio](https://developer.android.com/studio) in order to be able to build this project for android. 

After you have configured these two installations, simply in the root directory of the project run these two commands
```

npm install

react-native run-android

```

This will build the project and run the app for you. For the backend of this project checkout [E-Commerce-Web_And_Backend](https://github.com/Abdullah1428/E-Commerce-Shop-MERN-Stack) because you will need to have a backend running so that requests can be made from the app.

**Comment by r00tshaim** [comment]
Thanks for the info @Abdullah1428. Closing the issue.
